blog/api/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.ApiOverview, name='ApiOverview'),
    path('post-list/', views.postList, name='PostList'),
    path('post-detail/<int:pk>', views.postDetail, name='PostDetail'),
    path('post-create/', views.postCreate, name='PostCreate'),
    path('post-update/<int:pk>', views.postUpdate, name='PostUpdate'),
    path('post-delete/<int:pk>', views.postDelete, name='PostDelete'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

handler404 = views.error_404_view

blog/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('home/', views.home, name='home'),
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('create-post/', views.create_post, name='post'),
    path('edit-post/<int:pk>', views.edit_post, name='edit_post'),
    path('home/<str:ordering>', views.post_ordering, name='post_ordering'),
]

blog/api/models.py
from django.db import models

# Create your models here.

blog/main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=60)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.author) + "'s " + str(self.title)

blog/api/views.py
from main.models import Post
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import PostSerializer


# Create your views here.
@api_view(['GET'])
def ApiOverview(request):
    api_urls={
        'List':'/post-list/',
        'Detail View':'/post-detail/<str:pk>/',
        'Create': '/post-creat/',
        'Update': '/post-update/<str:pk>/',
        'Delete': '/task-delete/<str:pk>/',
    }
    return Response(api_urls)

@api_view(['GET'])
def postList(request):
    posts = Post.objects.all()
    serializer = PostSerializer(posts, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def postDetail(request,pk):
    post = Post.objects.get(id=pk)
    serializer = PostSerializer(post, many=False)
    return Response(serializer.data)


@api_view(['POST'])
def postCreate(request):
    serializer=PostSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
    return Response(serializer.data)


@api_view(['POST'])
def postUpdate(request,pk):
    post = Post.objects.get(id=pk)
    serializer=PostSerializer(instance=post, data=request.data)
    if serializer.is_valid():
        serializer.save()
    return Response(serializer.data)


@api_view(['DELETE'])
def postDelete(request, pk):
    post = Post.objects.get(id=pk)
    post.delete()
    return Response('Succesfully deleted!')

blog/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .form import *
from django.contrib.auth.decorators import login_required, permission_required
from .models import Post
from django.contrib.auth.models import User, Group


# Create your views here.
@login_required(login_url='/login')
def home(request, ordering=None):
    posts = Post.objects.all()
    if request.method == 'POST':
        post_id = request.POST.get('post-id')
        user_id = request.POST.get('user-id')

        if post_id:
            post = Post.objects.filter(id=post_id).first()
            if post and (post.author == request.user or request.user.has_perm('main.delete_post')):
                post.delete()
        elif user_id:
            user = User.objects.filter(id=user_id).first()
            if user and request.user.is_staff:

                if user.groups.filter(name="default").exists():
                    group = Group.objects.get(name="default")
                    group.user_set.remove(user)

                elif user.groups.filter(name="mod").exists():
                    group = Group.objects.get(name="mod")
                    group.user_set.remove(user)

    return render(request, 'main/home.html', {'posts': posts})


@login_required(login_url='/login')
@permission_required('main.add_post', login_url='/login', raise_exception=True)
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        print(form)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('/home')
    else:
        form = PostForm()

    return render(request, 'main/post.html', {'form': form})


@login_required(login_url='/login')
def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    print(post.id)
    print("test")
    if request.method == "POST":
        print(post)
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            print('OK')
            return redirect('/home')
    else:
        form = PostForm(instance=post)

    ctx = {
        'form': form,
        'post': post
    }
    return render(request, 'main/post_edit.html', ctx)
    

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/home')
    else:
        form = RegistrationForm()

    return render(request, 'registration/register.html', {'form': form})


def post_ordering(request, ordering):
    if request.method == 'GET':
        order_method = ordering[9:]
        if order_method == 'latest':
            ordered_posts = Post.objects.order_by('-created_at')
        else:
            ordered_posts = Post.objects.order_by('created_at')

    return render(request, 'main/home.html', {'posts': ordered_posts})


def error_404_view(request, exception):
    return render(request, 'main/404.html')

blog/main/templates/main/home.html
{% extends 'main/index.html' %}
{% load auth_extras %}
{% block title %}Blog page{% endblock%}
{% block content %}
<div class="d-flex justify-content-center align-items-center" id="post_ordering">
    <h3>Uporządkuj według:</h3>
    <div class="dropdown">
        <form method="GET">
            {% csrf_token %}
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="/static/icons8-menu.svg" width="32" height="32"/>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="ordering=latest">Data(najnowsze)</a></li>
                <li><a class="dropdown-item" href="ordering=oldest">Data(najstarsze)</a></li>
            </ul>
        </form>
    </div>
</div>
{% for post in posts %}
<div class="post_container">
    <div class="card text-center">
        <div class="card-header d-flex justify-content-between">
            <div class="d-flex align-content-center flex-wrap"> 
                <strong>@{{post.author}}</strong>
            </div>
            <div class="d-flex justify-content-center">
                <div>
                    {% if user == post.author or perms.main.delete_post %}
                        <form method="POST" >
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger" name="post-id" value="{{post.id}}">Delete</button>
                        </form>
                    {% endif %}
                </div>
                <div>
                    {% if user|has_group:"mod" and user != post.author %}
                        <form method="POST" >
                            {% csrf_token %}
                            <button type="submit" class="btn btn-warning" name="user-id" value="{{post.author.id}}">Ban user</button>
                        </form>
                    {% endif %}
                </div>
                <div>
                    {% if user == post.author or perms.main.change_post %}
                        <form method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-info"><a class="a-edit" href="{% url 'edit_post' pk=post.pk %}">Edit</a></button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card-body">
            <div>
                <h5 class="card-title">{{post.title}}</h5>
                <p class="card-text">{{post.description}}</p>
            </div>
        </div>
        <div class="card-footer text-muted">
            {{post.created_at}}
        </div>
    </div>
</div>
<hr>
{% empty %}
    <p>No posts yet :(</p>
{% endfor %}
{% endblock %}

blog/main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>{% block title %}Blog{% endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-secondary text-muted" id="nav">
        <div class="container-fluid">
            <div>
                <ul class="navbar-nav">
                    <li>
                        <img src="/static/napis-blog.svg" height="42" width="42"/>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/create-post">Post</a>
                    </li>
                </ul>
            </div>
            <div>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <span class="navbar-text">Logged in as {{user.username}} | </span>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/login">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">{% block content %}{% endblock %}</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

blog/main/templates/main/post.html
{% extends 'main/index.html' %}
{% block title %}Post{% endblock%}
{% load crispy_forms_tags %}
{% block content %}
    <br>
    <h2 class="text-center">Create a post!</h2>
    <form method="POST">
        {% csrf_token %}{{form|crispy}}
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
{% endblock %}

blog/main/templates/main/post_edit.html
{% extends 'main/index.html' %}
{% block title %}Post-edit{% endblock%}
{% load crispy_forms_tags %}
{% block content %}
    <br>
    <h2 class="text-center">Update a post!</h2>
    <form method="POST">
        {% csrf_token %}{{form|crispy}}
        <button class="btn btn-success" type="submit">Save</button>
    </form>
{% endblock %}